### ISSUE TITLE
Main url is wrong

### ISSUE THREAD

**Issue by gregfr** [apic-apps/apic-app-issues#11]
On Github, the main URL give (at least in two places) is "http://myapic.com".

![image](https://user-images.githubusercontent.com/361582/71544631-506c8d00-2982-11ea-9081-ac6886bdaffb.png)

![image](https://user-images.githubusercontent.com/361582/71544635-709c4c00-2982-11ea-81fa-618f2ce501ea.png)

**Comment by apic-apps** [comment]
Thanks for pointing that out. That was the old URL for APIC which is now www.apic.app. I have replaced the old one. Thanks again.
