### ISSUE TITLE
WebSocket Requests Not Working With Environment Variables

### ISSUE THREAD

**Issue by RodrigoFiedlerBatista** [apic-apps/apic-app-issues#12]
Hello,
So I have created a environment variable called "api_staging" which contains the url to my backend, and a websocket request that is using this variable on the url, requests that are not websocket work fine, but websocket requests show "undefined variable" when mousing over it.

**Comment by bjdash** [comment]
Working on it

**Comment by bjdash** [comment]
This has been fixed in version 2.3.6.
Let us know if you are still facing any issues.
