### ISSUE TITLE
request: Support for securityDefinitions

### ISSUE THREAD

**Issue by alevinetx** [apic-apps/apic-app-issues#13]
It would be greatly appreciated to support the security definitions:

https://swagger.io/docs/specification/2-0/authentication/basic-authentication/

Thank you!

**Comment by bjdash** [comment]
Support for adding securityDefinitions to you API projects is added in [version 2.3.7](https://apic.app/changelog.html).

To know more on how to add securityDefinitions visit the [documentation here](https://docs.apic.app/designer/api-security-definitions).

**Comment by bjdash** [comment]
Closed by mistake. Working on adding support for additionalProperties. Would be available in next release
