### ISSUE TITLE
ws tab css issues

### ISSUE THREAD

**Issue by fjxhkj** [apic-apps/apic-app-issues#14]
Please check out the .css of WS-TAB, that's look very un-pro:

- SendBtn always can't see
- SendTextArea always needs scroll down

Thank your guys for provides this amazing app, good luck!

**Comment by bjdash** [comment]
Thanks you for reporting the issue. Glad you like the app.
Could you please elaborate the styling issue you are facing? Also it would help a lot if you could share a screenshot of the css problem you are referring to help me understand the problem.

**Comment by bjdash** [comment]
Enhanced the CSS for websocket layout. Also added option to expand or collapse each section in socket tab. Let me know if this addresses your issue or not.
