### ISSUE TITLE
Can't ctrl-click on a Mac

### ISSUE THREAD

**Issue by DrRob** [apic-apps/apic-app-issues#3]
When configuring a Model Type, the UI says, "Hold Ctrl key to select multiple", but ctrl-clicking on a Mac causes the context menu to appear, and the selection does not change.

**Comment by apic-apps** [comment]
Fixed the issue in [latest version (#2.2.2)](https://chrome.google.com/webstore/detail/ggnhohnkfcpcanfekomdkjffnfcjnjam)
