### ISSUE TITLE
Importing Swagger fails silently

### ISSUE THREAD

**Issue by DrRob** [apic-apps/apic-app-issues#5]
When I tried to import a Swagger (OpenAPI) file using the Chrome Extension version, it failed silently.  In the Chrome Developer Tools console I see:

```
TypeError: Cannot read property '$ref' of undefined
    at services.js:1375
    at Object.p [as forEach] (angular.min.js:8)
    at services.js:1366
    at Object.p [as forEach] (angular.min.js:8)
    at services.js:1230
    at Object.p [as forEach] (angular.min.js:8)
    at Object.importOAS2 (services.js:1209)
    at importProj (designer-controller.js:260)
    at designer-controller.js:224
    at angular.min.js:136 "Possibly unhandled rejection: {}"
```

I believe the problem can be fixed by altering line 1375 of services.js from this:

`var ref = param.$ref;`

to this:

`var ref = resp.$ref;`

**Comment by apic-apps** [comment]
Fixed the issue in [latest version (#2.2.2)](https://chrome.google.com/webstore/detail/ggnhohnkfcpcanfekomdkjffnfcjnjam)
