### ISSUE TITLE
are there updated releases for platforms?

### ISSUE THREAD

**Issue by alevinetx** [apic-apps/apic-app-issues#7]
I love this tool.  I keep waiting for an update, as I'm on 2.2.7. I see there's a current web release, but the platforms are way behind.

will platforms be updated?
is this still in development?

**Comment by bjdash** [comment]
Glad to hear that you are liking this tool. I am adding support for graphql and will release an update sometime this week.

In the mean time if you want to use the latest version its available with a chrome extension https://chrome.google.com/webstore/detail/ggnhohnkfcpcanfekomdkjffnfcjnjam.

Nevertheless an update for windows and mac will be released this week.

**Comment by bjdash** [comment]
New build 2.3.2 has been published for the native apps. Please do share your feedback. Changelog for the new version can be found [here ](https://apic.app/changelog.html)
