### ISSUE TITLE
request: support for 'additionalProperties'

### ISSUE THREAD

**Issue by alevinetx** [apic-apps/apic-app-issues#9]
Is there a chance for supporting additionalProperties?

reference: https://swagger.io/docs/specification/data-models/dictionaries/

**Comment by bjdash** [comment]
Support for additional properties is added and available from version 2.3.12

**Comment by bjdash** [comment]
![image](https://user-images.githubusercontent.com/4252908/87839535-1ec20180-c893-11ea-8af4-fb80bf6a88bd.png)
